### ISSUE TITLE
Remove more files from the image

### ISSUE THREAD

**Issue by samdark** [shyim/wolfi-php#519]
I've inspected layers and found that some files could be removed from the image.

`RUN |1 PHP_VERSION=8.3 /bin/sh -c set -eo pipefail apk add --no-cache \ curl \ frankenphp-${PHP_VERSION} # buildkit`

![image](https://github.com/user-attachments/assets/1118292f-d9ee-4502-beb8-b3e99590d3d7)

The gain in size isn't huge, but I think it worth doing.

**Comment by shyim** [comment]
Good catch. I will make upstream PRs at Wolfi to remove them :)

**Comment by shyim** [comment]
Opend final PR then they are all gone :O

**Comment by shyim** [comment]
all are merged :)

**Comment by samdark** [comment]
Thank you!
