### ISSUE TITLE
PHP 8.4 support

### ISSUE THREAD

**Issue by neodc** [shyim/wolfi-php#594]
Any idea of when support for PHP 8.4 will be added? (No pressure obviously and thanks for your work in any case :smile:)

**Comment by neodc** [comment]
Not only, we use the caddy image (`ghcr.io/shyim/wolfi-php/caddy:8.3`).

Is it supposed to be already supported? I can't pull `ghcr.io/shyim/wolfi-php/caddy:8.4`

**Comment by shyim** [comment]
Are pushed :)
